### ISSUE TITLE
Flag

### ISSUE THREAD

**Issue by L-Kane** [flaghunters/Extra-Flags-for-int-#20]
Hi. Can you please add this flag for Baku, Azerbaijan?
Thanks in advance.
![az-baku](https://cloud.githubusercontent.com/assets/11041173/6224885/bbd6eef4-b69c-11e4-96f1-2248951b227b.gif)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
I'm no good at making flags but I've asked the wonderful people at /ref/ to create them for Azerbaijan.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Added Baku, made by ＰＢ. 70f6a7a11a
