### ISSUE TITLE
Add this County to Romania

### ISSUE THREAD

**Issue by Ayerev** [flaghunters/Extra-Flags-for-int-#21]
![cluj-county flag](https://cloud.githubusercontent.com/assets/11598379/6770850/827a86f0-d0c5-11e4-8023-460d569759dc.png)

Add this please
Country=Romania
County= Cluj

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Added!
https://github.com/flaghunters/Extra-Flags-for-int-/tree/master/flegs/Romania
