### ISSUE TITLE
Another County to Romania

### ISSUE THREAD

**Issue by Ayerev** [flaghunters/Extra-Flags-for-int-#22]
![neamt county](https://cloud.githubusercontent.com/assets/11598379/6771015/0fd92926-d0ca-11e4-9f48-ff3ef496b643.png)

County= Neamț
Thanks again!

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
If not one of the others add it in the meanwhile, I will add it tomorrow.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Added!

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
@Ayerev added as Neamt btw, cant have special characters to make sure all browsers display everything correctly.
