### ISSUE TITLE
Flag only appears when I reply to someone.

### ISSUE THREAD

**Issue by kalox** [flaghunters/Extra-Flags-for-int-#23]
Flag only appears when I reply to someone. When I make a post wihtout replying to a person it doesn't show. I'm using firefox.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
We cannot fix this due how 4chan was designed. Only when you make a post with the Quick Reply (replying to someone) an event is triggered. The Quick Reply says "Hey I just made a post" and that is how we can add another flag to your post. When you used the form at the top there is no such event so we cannot attach another flag to it.
I'd like to recommend that you keep using the quick reply or that you try one of the 4chan x front pages.

**Comment by kalox** [comment]
Ok, thanks for you answer.
