### ISSUE TITLE
pls add Porto - Portugal

### ISSUE THREAD

**Issue by ebinmeembroseph** [flaghunters/Extra-Flags-for-int-#24]

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Could you provide the 16x11 px png flag?

**Comment by olanzapine** [comment]
here, have some. there are still some missing i'll get to that late
![azores](https://cloud.githubusercontent.com/assets/11858351/7051839/ec02ad86-de22-11e4-9991-5b7f47617dcb.png)
r on
![beja](https://cloud.githubusercontent.com/assets/11858351/7051856/ff01c3c2-de22-11e4-905b-f0ac370352dd.png)
![braga](https://cloud.githubusercontent.com/assets/11858351/7051857/ff0899c2-de22-11e4-8af1-ae8bb15371ab.png)
![braganca](https://cloud.githubusercontent.com/assets/11858351/7051858/ff094ba6-de22-11e4-969f-9a3b4566b6c4.png)
![faro](https://cloud.githubusercontent.com/assets/11858351/7051859/ff0db236-de22-11e4-84fd-bead6051e6f6.png)
![madeira](https://cloud.githubusercontent.com/assets/11858351/7051860/ff0e6c62-de22-11e4-83e9-eb813cf6cfdd.png)
![porto](https://cloud.githubusercontent.com/assets/11858351/7051861/ff10e60e-de22-11e4-83a1-009fa0220c2b.png)
![santarem](https://cloud.githubusercontent.com/assets/11858351/7051862/ff2d26ca-de22-11e4-9535-8d5441829c1f.png)
![setubal](https://cloud.githubusercontent.com/assets/11858351/7051863/ff305926-de22-11e4-9f05-a734d78baabf.png)
![viana](https://cloud.githubusercontent.com/assets/11858351/7051864/ff31a182-de22-11e4-90e0-74d815098d66.png)
![vila_real](https://cloud.githubusercontent.com/assets/11858351/7051865/ff36b17c-de22-11e4-8e55-683986caffeb.png)

**Comment by olanzapine** [comment]
I also believe it'd be better to just have the coat-of-arms instead the whole flag

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Good job. I've added these, Viana was named just Viana and I changed it to Viana do Castelo.
